// Auto-generated imagery manifest - DO NOT EDIT MANUALLY
// Generated by scripts/generate-imagery-manifest.mjs

export type ImageryEntry = {
  key: string;
  src: string;
  w: number;
  h: number;
  lqip: string;
  color: string;
  variants: {
    src: string;
    w: number;
    h: number;
    type: "webp" | "orig";
  }[];
  credit?: string;
};

export const IMAGERY: Record<string, ImageryEntry> = {
  // This will be populated by the manifest generator
};

// Helper functions
export function pickBest(key: string, width: number, acceptWebp = true): { src: string; w: number; h: number } {
  const entry = IMAGERY[key];
  if (!entry) {
    console.warn(`Imagery key "${key}" not found in manifest`);
    return { src: '/images/placeholder.jpg', w: width, h: width };
  }

  // Filter variants by type preference
  const candidates = entry.variants.filter(v => 
    acceptWebp ? true : v.type === 'orig'
  );

  // Find the best fit (closest width >= requested, or largest available)
  const bestFit = candidates
    .filter(v => v.w >= width)
    .sort((a, b) => a.w - b.w)[0] || 
    candidates.sort((a, b) => b.w - a.w)[0];

  return bestFit || { src: entry.src, w: entry.w, h: entry.h };
}

export function getLqip(key: string): string {
  const entry = IMAGERY[key];
  if (!entry) {
    console.warn(`Imagery key "${key}" not found in manifest`);
    return 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAhEAACAQMDBQAAAAAAAAAAAAABAgMABAUGIWGRkqGx0f/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAECEgMRkf/aAAwDAQACEQMRAD8AltJagyeH0AthI5xdrLcNM91BF5pX2HaH9bcfaSXWGaRmknyJckliyjqTzSlT54b6bk+h0R//2Q==';
  }
  return entry.lqip;
}

export function getColor(key: string): string {
  const entry = IMAGERY[key];
  if (!entry) {
    console.warn(`Imagery key "${key}" not found in manifest`);
    return '#1a1a1a';
  }
  return entry.color;
}

export function getCredit(key: string): string | undefined {
  const entry = IMAGERY[key];
  return entry?.credit;
}

// Get all available imagery keys
export function getImageryKeys(): string[] {
  return Object.keys(IMAGERY);
}

// Get imagery by category (based on key prefix)
export function getImageryByCategory(category: string): Record<string, ImageryEntry> {
  return Object.fromEntries(
    Object.entries(IMAGERY).filter(([key]) => key.startsWith(`${category}/`))
  );
}
